### ISSUE TITLE
how to read a obj file with javaScript?

### ISSUE THREAD

**Issue by AndyLew528** [WesUnwin/obj-file-parser#8]
excuse me , I have a question about obj-file-parser,for example,I have a obj file,how can I parse it into fileContents,this obj file is only parse an obj file string? thx a lot ,it will helped me a lot .

**Comment by WesUnwin** [comment]
If you have a javascript File object, if thats what your saying, you can read the file obtaining the contents of it as a multi-line string:

In this example I'm using the FileReader API:  https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsText and assuming your doing this in some browser that supports this:

` using FileReader:

   function readFile(file) {
        const reader = new FileReader();
        reader.readAsText(file);
        reader.onload = function() {
            const fileContents = reader.result;
            // Use the obj file's contents (as a string) here
        };
    }
`
You may obtain the File object by any means, for example using an input element of type file:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file which allows the user to choose a local file on their computer.

Another example, for using this in the context of Node JS might be:

`var fileContents = require("fs").readFileSync("file.obj", 'utf8')`

By design, I'm accepting the obj file as a string so its versatile enough to handle other situations, like for example obtaining the obj data from the server via an window.fetch() request, and to ensure the library is not dependent on file reading APIs which are platform specific as you can see in the above examples.

**Comment by AndyLew528** [comment]
Thank you very much for your answer,It give me a new way of thinking,Maybe I can creat a new filetype input element to read this file.
